baseurl = "https://epic-brown-c300a5.netlify.com/"
languageCode = "en"
title = "The Campus Journalist"
theme = "hemingway2"
googleAnalytics = ""
description = "21st century opinions on student affairs"
keywords = ["student", "journalism", "university"]

[taxonomies]
tag = "tags"
category = "categories"

